title: The Thought Experiment 2020
author: Harley Riddle
email: harley@crypticsight.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my thought experiment. 

# social links
twitter_username: your-twitter-handle
github_username:  riddleharley971

show_excerpts: true # set to false to remove excerpts on the homepage
